services:
  amd64:
    image: smasherofallthings/ansible:amd64-${Tag:-latest}
    build:
      context: '.'
      dockerfile: Dockerfile
      pull: true
      args:
        BaseImage: smasherofallthings/base-python:amd64-latest
      platforms:
        - "linux/amd64"
